name: CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.zig'
      - '.github/workflows/CI.yml'
  push:
    branches:
      - main
    paths:
      - '**.zig'
      - '.github/workflows/CI.yml'

jobs:
  test:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        zig-version: [0.13.0, master]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ matrix.zig-version }}
      - name: fmt and test(windows)
        if: matrix.os == 'windows-latest'
        run: |
          zig.exe fmt --check .
          zig.exe build
          zig.exe build test
      - name: fmt and test(unix)
        if: matrix.os != 'windows-latest'
        run: |
          zig fmt --check .
          zig build
          zig build test
      - name: download test(ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          bash .github/test.sh
